Add bookings
TimurDV88/java-shareit pull request #2
Opened 2023-07-25 09:25 UTC by TimurDV88

2023-07-25 18:27 UTC, EugeneLenkevich requested changes
Привет, Тимур, спасибо за PR

В целом супер, единственное постарайся переложить сортировку и выборку данных на СУБД, она это умеет делать гораздо эффективнее чем в приложении в цикле руками фильтровать :)

2023-07-25 18:27 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (item.getOwnerId().equals(bookerId)) {
А не лучше ли было бы в запрос выше добавить условие в запрос чтобы он искал только вещи текущего пользователя, в случае чего чужих вещей он бы просто не нашел и проверять потом ничего не надо было бы :)

2023-07-25 18:27 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (!isApproved) {
Или так, в одну строку еще можно :)

booking.setStatus( IsApproved ?  BookingStatus.APPROVED : BookingStatus.REJECTED)

2023-07-25 18:27 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .filter(b -> b.getStart().isBefore(currentTime) && b.getEnd().isAfter(currentTime))
Фильтровать стоит сразу в запросе, на стороне СУБД, а сюда, на сторону приложения, тащить данные все же очень накладно, так никакой памяти не хватит :)

2023-07-25 18:27 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        bookingList = getListByStatus(bookingList, requestStatus);
Идея понятна что ты хотел сделать чтобы не возится со всеми этими вариантами сортировок, ноя  предложу еще вот что, если есть желание. Можешь попробовать применить паттерн "стратегия"

Возможно, именно для этого случая стратегия покажется избыточной (обработчики все в одну строчку), но попробовать самое то, к тому же в реальной жизни часто используется, так как часто в обработчике бывает нетривиальная логика и куча своих зависимостей :) 

Смысл такой. У тебя есть соответствие между состоянием и обработчиком этого состояния.
Можно сделать мапу
Map<String, BookingStateFetchStrategy>, где BookingStateFetchStrategy - который будут реализовывать обработчики состояния

или же, более простой вариант, в мапу засунуть методы сервиса, примерно так будет
Map<String, Supplier> handlers = ...
handlers.put("ALL", this::handleAllState) 

То есть, мы заменяем switch (который далее в методе) на поиск нужного обработчика через map :)

https://ravthiru.medium.com/strategy-design-pattern-with-in-spring-boot-application-2ff5a7486cd8

2023-07-25 18:27 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/util/StringsForSQL.java
> +            "WHERE b.id = ?1 " +
Лучше использовать плейсхолдеры чем номера переменных. Вот, кстати. Методы и запросы разнесены и с ходу и не прикинуть какой там параметр был в метод не сходив и не посмотрев его, по этому не над лишнего мудрить :)

2023-07-25 18:27 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/util/StringsForSQL.java
> +            "SELECT new ru.practicum.shareit.booking.dto.DbBookingDto(b.id, b.start, b.end, b.status, " +
А не проще было вытаксивать саму сущность Booking а потом ее уже в dto перекладывать. Если ообще надо столько всяких раных dto...
Вообще, писать гоалый sql довольно муторно и код такой тяделовато поддерживать. Плюс это может быть преджевременной оптимизацией так как хибер(ORM) на самый тупой инстурмент, в нем есть кэши, два уровня, далее мы можем сами регулировать то, каким образом вытаскивать связанные сущности. В общем ORM сильно упрощает жизнь, не всегда стоит вручную дто-шки набивать. Но уж не передлывай, пусть так будет :)


PS
Хоть вроде как в проекте связи и не используются но все же отмечу вот что, для общем информациина будущее плюс для понимания насколько можно настраивать движок ORM в разрезе динамической оптимизации запросов.

Если связи LAZY (а они по умолчанию такие), то эти данные не выгребаются из БД при обращении к родительской сущности, а вот при обращении к полю каждого объекта инициируется соответствующий запрос. И так мы иногда будем порлучать проблему N+1 запросов. Для того чтобы избавится от этой пробелмы мы можем явно указывать в конкретном запросе что надо вытащить еще и связанные ленивые коллекции с помощью join fetch

![image](https://user-images.githubusercontent.com/94845100/194059305-413c94fd-e9da-40d1-8090-05568e0cc255.png)


https://stackoverflow.com/questions/17431312/what-is-the-difference-between-join-and-join-fetch-when-using-jpa-and-hibernate

Или еще вот, entity graph
https://sysout.ru/entity-graph-v-spring-data-jpa/

2023-07-26 05:30 UTC, TimurDV88 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (item.getOwnerId().equals(bookerId)) {
Привет! Не совсем понял про поиск вещей текущего пользователя, мы же создаём новое бронирование, там могут быть любые вещи?

2023-07-26 05:31 UTC, TimurDV88 commented on src/main/java/ru/practicum/shareit/TestController.java
> +public class TestController {
Забыл почистить его)

2023-07-26 05:58 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (item.getOwnerId().equals(bookerId)) {
Имею в виду вот что. Мы достаем вещь по ид и, далее, начинаем ее проверять, можно было все эти проверки добавить сразу в запрос и в итоге, если вещь недоступна по какой-то причине мы бы просто ее и не нашли и все

Хотя, если подумать, мы бы не вывели информацию, а почему именно не получилось найти.. И может тесты это исключение  проверяют. В общем как то так :)


![image](https://github.com/TimurDV88/java-shareit/assets/109306643/f9d2cf09-9f12-4a76-90a7-4080b2cd18ae)

2023-07-26 06:12 UTC, TimurDV88 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (item.getOwnerId().equals(bookerId)) {
Ага, понял, но да, нужно учитывать постман, для него проще иметь все проверки отдельно, так как в некоторых тестах проверяются типы исключений и всё это нужно отлавливать и подгонять)

2023-07-26 10:12 UTC, TimurDV88 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        bookingList = getListByStatus(bookingList, requestStatus);
Здесь я что-то застопорился. Так как постман просит возвращать дто, в котором есть вложенные объекты (booker и item), а не просто объект с нужными полями, то из базы нужно тащить кастомный класс через JPQL, да? Иначе придётся отдельно обращаться за booker и item и потом уже собирать их в приложении. При этом есть две аналогичных стратегии отбора бронирований по их статусам, которые отличаются только условием поиска - либо по i.ownerId либо по b.bookerId. В итоге я не вижу вариантов для отбора по статусу на стороне базы, кроме как дважды писать аналогичные запросы, которые отличаются только одним условием. 

Я поэтому изначально и тащил все бронирования конкретных пользователей, чтобы их уже потом обработать. Своего рода компромисс - вроде бы и не слишком много тащить из базы (не вообще все бронирования, а только по условиям поиска) и обрабатывать можно по одному алгоритму согласно статусу.

Как лучше поступить в этом случае?

2023-07-26 10:32 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        bookingList = getListByStatus(bookingList, requestStatus);
> Своего рода компромисс - вроде бы и не слишком много тащить из базы

Опасный компромис ))
В реальной жизни обязательно будут ситуации, когда данных окажется много, какой нибудь 1 пользователь будет иметь много бронирований. При каждом его заходе в систему она будет падать, неожиданно так, поддержка будет пить корвалол в поисках причины. Ну или пользователи массово зайдут в систему (под новый год например, под какую то акцию и пр) , она тоже может упасть.
Плюс еще сортировку с пагинацией так нормально не сделать,  придется всегда тащить все данные

///
Про сортировку
1. таки да сделать несколько разных методов с разной сортировкой
2. хоть это и будет далее, не сейчас, но тем не менее - сортировку можно задать через Pageable https://www.baeldung.com/spring-data-jpa-pagination-sorting
3. есть и другие методы, когда мы запрос формируем динамически, например, через JPA Specification API, но это муторно и долго, проще взять решение из п.1. :)  https://spring.io/blog/2011/04/26/advanced-spring-data-jpa-specifications-and-querydsl

///

Про то как вытаскивать связанные сущности

Мы можем явно указывать в конкретном запросе что надо вытащить еще и связанные ленивые коллекции с помощью join fetch

![image](https://user-images.githubusercontent.com/94845100/194059305-413c94fd-e9da-40d1-8090-05568e0cc255.png)


https://stackoverflow.com/questions/17431312/what-is-the-difference-between-join-and-join-fetch-when-using-jpa-and-hibernate

Или еще вот, entity graph
https://sysout.ru/entity-graph-v-spring-data-jpa/

Надеюсь все ответил, что то еще осталось? :)

2023-07-26 10:34 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        bookingList = getListByStatus(bookingList, requestStatus);
А. Да. ты не используешь аннотации-связи OneToMany, ManyToOne и пр, так тебе все придеться руками разгребать, то есть начать лучше c того что описать связи между табличками/сущностями

2023-07-26 10:36 UTC, TimurDV88 commented on src/main/java/ru/practicum/shareit/util/StringsForSQL.java
> +            "SELECT new ru.practicum.shareit.booking.dto.DbBookingDto(b.id, b.start, b.end, b.status, " +
Здесь я немного оптимизировал дто-шку, она теперь собирается из трёх базовых сущностей: SELECT new ru.practicum.shareit.booking.dto.DbEntityBookingDto(b, u, i) и т.д.

2023-07-26 11:13 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/util/StringsForSQL.java
> +            "SELECT new ru.practicum.shareit.booking.dto.DbBookingDto(b.id, b.start, b.end, b.status, " +
Ну, да, это и есть разгребание вручную :)

2023-07-27 09:20 UTC, TimurDV88 commented on src/main/java/ru/practicum/shareit/util/StringsForSQL.java
> +            "SELECT new ru.practicum.shareit.booking.dto.DbBookingDto(b.id, b.start, b.end, b.status, " +
Всё, разобрался, большое спасибо за совет внедрить связи, всё сразу получилось)

2023-07-27 09:26 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/util/StringsForSQL.java
> +            "SELECT new ru.practicum.shareit.booking.dto.DbBookingDto(b.id, b.start, b.end, b.status, " +
Собвственно, да,  в этом и заключается сила ORM, он заьирает на себя все это преекладывание полей :)
Но иногда бывает надо и SQL руками пописать, для этого есть свои фреймворки, MyBatis например

2023-07-27 09:27 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-08-04 06:06 UTC, merged